name: iso8601_offset
description: Provide a string containing offset information that is not processed by `DateTime.toIso8601String()`.
version: 1.2.0
homepage: https://github.com/koji-1009/iso8601_offset

environment:
  sdk: ^3.11.0

dependencies:
  json_annotation: ^4.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.31.0
